#!/bin/bash

CMSSW=CMSSW_4_2_6

cmsrel $CMSSW
cd $CMSSW/src
cmsenv


# susypat
addpkg PhysicsTools/Configuration    V00-10-13
addpkg MuonAnalysis/MuonAssociators  V01-13-00

# For deterministic FastJet-rho
addpkg RecoJets/Configuration       V02-04-17

# tau update
addpkg DataFormats/TauReco          V01-00-07-01
addpkg RecoTauTag/TauTagTools       V01-00-12
addpkg RecoTauTag/RecoTau           V01-00-33-06 

cvs co -rV15-03-06 -dSUSYBSMAnalysis/SusyCAF UserCode/SusyCAF
