#!/bin/bash

export SCRAM_ARCH=slc5_amd64_gcc462
CMSSW=CMSSW_5_2_4_patch1

cmsrel $CMSSW
cd $CMSSW/src
cmsenv

# susypat (https://twiki.cern.ch/twiki/bin/viewauth/CMS/SusyPatLayer1DefV12)
addpkg DataFormats/PatCandidates   V06-05-00
addpkg PhysicsTools/PatAlgos       V08-09-02
addpkg PhysicsTools/PatUtils       V03-09-18-03
addpkg CommonTools/ParticleFlow    V00-03-08
addpkg RecoParticleFlow/PFProducer V15-01-06
addpkg FWCore/GuiBrowsers          V00-00-60
addpkg PhysicsTools/Configuration  V00-12-00

#MET filters
cvs co -r lhx_14APR2012_v1 RecoMET/METFilters
#cvs co -r lhx_24APR2012_v2 RecoMET/METFilters

#cvs co -dSUSYBSMAnalysis/SusyCAF UserCode/SusyCAF
cvs co -rV17-pre3 -dSUSYBSMAnalysis/SusyCAF UserCode/SusyCAF


## TODO ##
# taus (https://twiki.cern.ch/twiki/bin/view/CMS/SusyPatLayer1DefV12)
# rho25 for photons (https://twiki.cern.ch/twiki/bin/view/CMS/Vgamma2011PhotonID)
# store multiple rhos
# check severity level adjustments
