#!/bin/bash 
export SCRAM_ARCH=slc5_amd64_gcc462 
CMSSW=CMSSW_5_3_11
cmsrel $CMSSW 
cd $CMSSW/src 
cmsenv 

#PAT (https://twiki.cern.ch/twiki/bin/view/CMSPublic/SWGuidePATReleaseNotes52X#V08_09_62)
addpkg DataFormats/PatCandidates V06-05-06-12 
addpkg PhysicsTools/PatAlgos     V08-09-62
addpkg PhysicsTools/PatUtils
addpkg RecoBTag/ImpactParameter V01-04-09-01
addpkg RecoBTag/SecondaryVertex V01-10-06
addpkg RecoBTag/SoftLepton      V05-09-11
addpkg RecoBTau/JetTagComputer  V02-03-02
addpkg RecoBTag/Configuration   V00-07-05
addpkg RecoParticleFlow/PFProducer V15-02-06

#additional packages from SusyPAT (https://twiki.cern.ch/twiki/bin/viewauth/CMS/SusyPatLayer1DefV12#Installation_recipe)
addpkg DataFormats/StdDictionaries    V00-02-14
addpkg FWCore/GuiBrowsers             V00-00-70
addpkg CommonTools/RecoUtils          V00-00-13
addpkg JetMETCorrections/Type1MET     V04-06-09
addpkg PhysicsTools/Configuration     V00-12-07

#MET Filters (https://twiki.cern.ch/twiki/bin/view/CMS/MissingETOptionalFilters#A_Central_Filter_Package_RecoMET)
cvs co -r V00-00-13-01 RecoMET/METFilters
cvs co -r V00-00-08 RecoMET/METAnalyzers

# functions to compute electron and photon IDs (https://twiki.cern.ch/twiki/bin/view/CMS/EgammaPFBasedIsolation#Example_for_photons)
cvs co -r V09-00-01 RecoEgamma/EgammaTools       
cvs co -r SE_PhotonIsoProducer_MovedIn EgammaAnalysis/ElectronTools
cvs co -r SE_PhotonIsoProducer_MovedOut UserCode/EGamma/EGammaAnalysisTools/python/photonIsoProducer_cfi.py
cp UserCode/EGamma/EGammaAnalysisTools/python/photonIsoProducer_cfi.py EgammaAnalysis/ElectronTools/python/
rm -rf UserCode/
# pdf reweighting utilities ( needed for proper setup of lhapdffull https://twiki.cern.ch/twiki/bin/view/CMSPublic/SWGuideEWKUtilities#Code_and_tags)
cvs co -r CMSSW_5_3_3_patch2 ElectroWeakAnalysis/Utilities

git clone https://github.com/bainbrid/SusyCAF.git -b V18-1 SUSYBSMAnalysis/SusyCAF
# adding nominal pdf
unalias cp
cp -p SUSYBSMAnalysis/SusyCAF/plugins/mods/PdfWeightProducer.cc ElectroWeakAnalysis/Utilities/src/

scram setup lhapdffull
touch $CMSSW_BASE/src/ElectroWeakAnalysis/Utilities/BuildFile.xml #to ensure recompilation of the whole package

scram b -j12
