#!/bin/bash

export SCRAM_ARCH=slc5_amd64_gcc462
CMSSW=CMSSW_5_3_2_patch4

cmsrel $CMSSW
cd $CMSSW/src
cmsenv

addpkg DataFormats/PatCandidates       V06-05-01
addpkg PhysicsTools/PatAlgos           V08-09-21
addpkg PhysicsTools/PatUtils           V03-09-23
addpkg CommonTools/ParticleFlow        V00-03-15
addpkg CommonTools/RecoUtils           V00-00-12
addpkg JetMETCorrections/Type1MET      V04-06-09
addpkg RecoParticleFlow/PFProducer     V15-01-11

addpkg PhysicsTools/Configuration        V00-12-03

#MET filters (https://twiki.cern.ch/twiki/bin/view/CMS/MissingETOptionalFilters)
cvs co -r V00-00-07 RecoMET/METFilters
#Add? This is for CSC beam halo
cvs co -r V00-00-08 RecoMET/METAnalyzers
 

# functions to compute electron IDs
cvs co -r CutBasedId_V00-00-02 -d EGamma/EGammaAnalysisTools UserCode/EGamma/EGammaAnalysisTools

cvs co -dSUSYBSMAnalysis/SusyCAF -r V17-0 UserCode/SusyCAF

#unalias cp
cp -p SUSYBSMAnalysis/SusyCAF/python/mods/SUSY_pattuple_cff.py PhysicsTools/Configuration/python/SUSY_pattuple_cff.py
cp -p SUSYBSMAnalysis/SusyCAF/python/mods/jetTools.py PhysicsTools/PatAlgos/python/tools/
 

