#!/bin/bash

export SCRAM_ARCH=slc5_amd64_gcc462
CMSSW=CMSSW_5_2_3

cmsrel $CMSSW
cd $CMSSW/src
cmsenv

# susypat
addpkg PhysicsTools/PatAlgos       V08-08-25
addpkg PhysicsTools/PatUtils       V03-09-18-03
addpkg CommonTools/ParticleFlow    V00-03-07-01
addpkg RecoParticleFlow/PFProducer V15-01-05

addpkg PhysicsTools/Configuration  V00-12-00

#MET filters
cvs co -r lhx_10APR2012_v1 RecoMET/METFilters

cvs co -dSUSYBSMAnalysis/SusyCAF UserCode/SusyCAF
#cvs co -rV17-pre1 -dSUSYBSMAnalysis/SusyCAF UserCode/SusyCAF
